---
version: '3'
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - XXXX:XXXX
    volumes:
      - ./homepage/app/config:/app/config # Make sure your local config directory exists
      - ./homepage/app/public/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true" #optional, enable if using watchtower